version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tps
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  app:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/tps"
      CELERY_BROKER_URL: "pyamqp://guest@rabbitmq//"
    ports:
      - "8000:8000"
