apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tps-monitor
spec:
  selector:
    matchLabels:
      app: tps
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
